apiVersion: batch/v1
kind: Job
metadata:
  name: bin-bash
spec:
  template:
    spec:
      containers:
      - name: bin-bash
        image: rootproject/root:6.32.02-ubuntu24.04
        command: ["/bin/bash"]
      restartPolicy: Never  
  backoffLimit: 4 

